In [3]:
import numpy as np
#import random

In [2]:
a = [1, 2, 3]
[q*2 for q in a]

[2, 4, 6]

In [9]:

a = np.array([1, 2, 3])
a * 2

array([2, 4, 6])

In [11]:
a = [1, 2, 3]
b = [4, 5, 6]
[q + r for q, r in zip(a, b)]

[5, 7, 9]

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a + b

array([5, 7, 9])

In [30]:
a = np.zeros(4, int)
a

array([0, 0, 0, 0])

In [21]:
c = np.zeros_like(a).astype(float)
c

array([0., 0., 0., 0.])

In [46]:
a = np.arange(1, 10000, 3)
a

array([   1,    4,    7, ..., 9991, 9994, 9997])

In [36]:
l = [np.random.randint(0, 10, 3)]
l

[array([7, 1, 1])]

In [38]:
b = [np.random.rand(6)]
b

[array([0.66755945, 0.31911986, 0.84208116, 0.95659197, 0.62789225,
        0.65256634])]

In [40]:
b = [np.random.randn(6)]
b

[array([-0.03205997,  0.2806709 ,  1.16311887,  0.24667396, -1.87459887,
        -1.88690852])]

In [44]:
b = [np.random.uniform(4,5,7)]
b

[array([4.31144852, 4.29050348, 4.68439348, 4.62522492, 4.88928837,
        4.9310835 , 4.88611895])]

In [52]:
c = [np.random.normal(5,2,7)]
c

[array([4.63343229, 3.55598464, 3.61215767, 2.6601184 , 5.5108224 ,
        5.11554529, 5.90193995])]

In [57]:
rng = np.random.default_rng()

In [58]:
rng.integers(0,20,6)

array([ 9, 12, 11,  9,  0, 13], dtype=int64)

In [61]:
rng.random(3)

array([0.94117748, 0.65078958, 0.41553446])

In [64]:
rng.standard_normal(3)

array([-1.183447  , -0.89001483,  1.27441416])

In [75]:
a = [2,5,3]
a [2:5] = [5,9]
a

[2, 5, 5, 9]

In [76]:
np.sqrt([25,9])

array([5., 3.])

In [52]:
np.max([6,76,89, 1])

89

In [79]:
np.min([6,76,89, 1])

1

In [81]:
np.sum([6,76,89, 1])

172

In [84]:
import math

In [59]:
a = np.arange(6)
b = a.reshape(-1,1)
b

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [6]:
np.allclose(0,2+0,8-0,1,0)

True

In [9]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.random.randint(1,20, (3,3))

array([[19, 16,  9],
       [ 6,  7, 14],
       [12, 10,  6]])

In [36]:
a = [[1,4,7],[2,5,8],[3,6,9]]
b = [[10,13,16],[11,14,17],[12,15,18]]
c = [[20,23,26],[21,24,27],[22,25,28]]
d = np.column_stack((a,b))
e = np.vstack((a,c))
f = np.delete(a,[2], axis=0)
g = np.pad(b,1)
g

array([[ 0,  0,  0,  0,  0],
       [ 0, 10, 13, 16,  0],
       [ 0, 11, 14, 17,  0],
       [ 0, 12, 15, 18,  0],
       [ 0,  0,  0,  0,  0]])

In [47]:
i,j=np.arange(2),np.arange(5)
I,J=np.meshgrid(i,j,sparse=true,indexing'ij')

SyntaxError: positional argument follows keyword argument (735943310.py, line 2)

In [49]:
a = np.floor([2.3, 1.9,3.5, 9, 1.25])
a

array([2., 1., 3., 9., 1.])

In [50]:
a = np.round([2.3, 1.9,3.5, 9, 1.25])
a

array([2., 2., 4., 9., 1.])

In [51]:
a = np.ceil([2.3, 1.9,3.5, 9, 1.25])
a

array([3., 2., 4., 9., 2.])

In [73]:
a = [[1,2],[3,4]]
print(a)
b = a.repeat(3, axis=1)
print(b)

[[1, 2], [3, 4]]


AttributeError: 'list' object has no attribute 'repeat'

In [79]:
a = [[1,2],[3,4]]
np.where(a==2)[0][0]
next(i[0]for i, v in np.ndenumerate(a) if v==3)
np.searchsorted(a,2)

IndexError: index 0 is out of bounds for axis 0 with size 0

In [77]:
a = np.array([[3,4,9,20],[2,6,9,47],[3,12,5,87],[48,6,30,23]])
print(a)
print("A l'indice 1 et 2 se trouve : ",a[1,2])
print("Sur la ligne 1 se trouve : ",a[1,:])
print("Dans la colonne 2 se trouve : ",a[:,3])
print("Le maximum de a est : ",a.max())
print("Le minimum de a est : ",a.min())
print(" A l'indice [:,1:3] on a : \n", a[:,1:3])
print(" A l'indice [::3,0::3] on a : \n", a[::3,0::3])
print(" A l'indice a[-2:,-2:] on a : \n", a[-2:,-2:])
print("La somme du tableau a est : \n",a.sum())
b = a.sum(axis=1) 
print("La somme des lignes du tableau a est : \n",b.reshape(-1,1))
print("La somme des colonnes du tableau a est : \n",a.sum(axis=0))

[[ 3  4  9 20]
 [ 2  6  9 47]
 [ 3 12  5 87]
 [48  6 30 23]]
A l'indice 1 et 2 se trouve :  9
Sur la ligne 1 se trouve :  [ 2  6  9 47]
Dans la colonne 2 se trouve :  [20 47 87 23]
Le maximum de a est :  87
Le minimum de a est :  2
 A l'indice [:,1:3] on a : 
 [[ 4  9]
 [ 6  9]
 [12  5]
 [ 6 30]]
 A l'indice [::3,0::3] on a : 
 [[ 3 20]
 [48 23]]
 A l'indice a[-2:,-2:] on a : 
 [[ 5 87]
 [30 23]]
La somme du tableau a est : 
 314
La somme des lignes du tableau a est : 
 [[ 36]
 [ 64]
 [107]
 [107]]
La somme des colonnes du tableau a est : 
 [ 56  28  53 177]


In [70]:
a = np.array([[3,6],[4,4]])
b = np.array([[2,0],[6,7]])
print(a)
print(b)
print(a@b)
print(a*b)
print(a-b)
a.dtype
a.shape

[[3 6]
 [4 4]]
[[2 0]
 [6 7]]
[[42 42]
 [32 28]]
[[ 6  0]
 [24 28]]
[[ 1  6]
 [-2 -3]]


(2, 2)

In [67]:
a = np.array([[2,54,7],[3,1,8]])
print(a)
print("Voici la tranposé de a : \n",a.transpose())

[[ 2 54  7]
 [ 3  1  8]]
Voici la tranposé de a : 
 [[ 2  3]
 [54  1]
 [ 7  8]]
